v0.0.1
htmlacademy-htmlcss/1277559-sedona-30 pull request #2
Opened 2021-01-25 18:10 UTC by mejer404

Разметка главной страницы

Co-Authored-By: mejer404 <61515267+mejer404@users.noreply.github.com>

2021-01-25 21:13 UTC, AlexanderGJJ requested changes

2021-01-25 21:13 UTC, AlexanderGJJ commented on index.html
> +    </a>
Отсутствует открывающий тег 'a'

2021-01-25 21:13 UTC, AlexanderGJJ commented on index.html
> +          <li><a href="blank.html">ФОТО И ВИДЕО</a></li>
Капсом писать не обязательно, такое отображение делается с помощью css

2021-01-25 21:13 UTC, AlexanderGJJ commented on index.html
> +          <li><a href="blank.html">ГОСТИНИЦЫ</a></li>
Тут href можно заменить на страницу каталога

2021-01-25 21:13 UTC, AlexanderGJJ commented on index.html
> +        <figure>
figure используется для иллюстрация, в нашем случае это просто декоративная иконка

2021-01-25 21:13 UTC, AlexanderGJJ commented on index.html
> +    </section>
Отсутствует открывающий тег section
Пункты №1 по №5 можно объединить в один общий список(у тебя сейчас они разделены на несколько), т.к тут явно идет перечисление пунктов

2021-01-25 21:13 UTC, AlexanderGJJ commented on index.html
Не размечена форма и футер. Их тоже нужно разметить в этом задании

2021-01-27 10:23 UTC, AlexanderGJJ requested changes

2021-01-27 10:23 UTC, AlexanderGJJ commented on index.html
> +          <li><a href="blank.html">фото и видео</a></li>
Первую букву в слове с заглавной лучше писать, так же как и в правилах русского языка все

2021-01-27 10:23 UTC, AlexanderGJJ commented on index.html
> +    <a><img src="img/nastojashigorodok.svg" width="286" height="164" alt="фото городка"></a>
Лишний тег a, если есть тег a, должен быть и переход по href куда-то. В нашем случае таких переходов нет. Замечание относится к остальным картинкам так же в этом section

2021-01-27 10:23 UTC, AlexanderGJJ commented on index.html
> + <table border="1">
Посмотри в учебнике для чего используется тег table. Тут он не подходит, достаточно разметить форму

2021-01-27 10:23 UTC, AlexanderGJJ commented on index.html
> +        <form><p><i>дата заезда</i></p>
Тег i используется для того чтобы сделать текс курсивом. В макете этого нет и если нужен где-то курсив, то проще сделать через css

2021-01-27 10:23 UTC, AlexanderGJJ commented on index.html
> +        <option value="day">нет текста</option>
Это обычный импут, на макете нет селекта

2021-01-27 10:23 UTC, AlexanderGJJ commented on index.html
> +      <input type="submit" value="Найти">
интуп лучше заменить на button, инпут это скорее про ввод данных от пользователя

2021-01-27 10:23 UTC, AlexanderGJJ commented on index.html
> + <footeer> <ul>
footeer ошибка в написании тега. Предлагаю проверить всю верстку на валидаторе

2021-01-27 17:54 UTC, mejer404 commented
Исправлены правки по дз

2021-01-27 20:01 UTC, merged