Стилизация главной страницы
htmlacademy-htmlcss/1277559-sedona-30 pull request #4
Opened 2021-02-14 19:12 UTC by mejer404

добавлены два новых цвета.
Изменен футер, карта вынесена в отдельный раздел.
скрыты заголовки, которые не отображаются.
исправления по комментариям.

2021-02-15 18:48 UTC, AlexanderGJJ requested changes

2021-02-15 18:48 UTC, AlexanderGJJ commented on css/style.css
>    --special: #81B3D2;
special, по сравнению с другими переменными, эта не совсем понятно что означает.

2021-02-15 18:48 UTC, AlexanderGJJ commented on css/style.css
>  .site-navigation-current a:not([href]) {
a:not([href], если добавится href такой селектор не будет работать.
site-navigation-current вообще нет в разметке

2021-02-15 18:48 UTC, AlexanderGJJ commented on css/style.css
> +  line-height: 26px;
Заголовок внутри блока intro не унаследовал font-size и line-height

2021-02-15 18:48 UTC, AlexanderGJJ commented on css/style.css
> +.featuresvs-list{
featuresvs, ошибка в написании слова. Нужно везде этот момент поправить

2021-02-15 18:48 UTC, AlexanderGJJ commented on css/style.css
> +.featuresvs-item1 {
featuresvs-item1. у тебя из-за того что на теге только этот класс не применились стили к элементам которые ты стилизуешь через featuresvs-item. featuresvs-item должен быть на каждом элементе списка + нужно еще что-то чтобы ты мог дополнительно добавить фон для 2х элементов с синим фоном

2021-02-15 18:48 UTC, AlexanderGJJ commented on css/style.css
>  .features-list {
Название с первым списком слишком похожи, выбери какое-то другое название.
Так же нужно добавить стили к элементам внутри этого списка, сейчас этого нет(заголовки).
Тегом img не нужно размечать иконки. Эти иконки декоративные

2021-02-15 18:48 UTC, AlexanderGJJ commented on css/style.css
> +.invitation{
Заголовок и параграф внутри этого блока без стилей

2021-02-15 18:48 UTC, AlexanderGJJ commented on css/style.css
> +  line-height: 21px;
На макете другие стили, перепроверь

2021-02-15 18:48 UTC, AlexanderGJJ commented on css/style.css
> +  line-height: 21px;
На макете другие стили, перепроверь

2021-02-15 18:48 UTC, AlexanderGJJ commented on css/style.css
> +}
У списка с соц сетями можно обнулить дефолтные стили сейчас

2021-02-15 18:48 UTC, AlexanderGJJ commented on index.html
> +  <content class="map">
Замени пока на обычный див

2021-02-15 18:48 UTC, AlexanderGJJ commented on css/style.css
>    font-weight: 700;
не понятно откуда взял 24px, на макете не нашел.
Можно выбрать высоту строки, которая чаще всего используется и использовать ее в этом месте.

2021-02-20 16:08 UTC, mejer404 reviewed
информация принята к исправлению

2021-02-21 07:31 UTC, merged